Include:
```{r}
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(zoo)
library(tibble)
library(outliers)
```




READ IN DATA
```{r}

get_url <- function(year) {
  paste0("https://www.ndbc.noaa.gov/view_text_file.php?filename=44013h", year, ".txt.gz&dir=data/historical/stdmet/")
}

#=======================================================
#INITIATE DATAFRAME WITH 1985 DATA
year1<-"1985"
buoy<-read.table(get_url(year1), header = TRUE, sep = "", na.strings = "MM", fill = TRUE)

header=scan(get_url(year1),what= 'character',nlines=1)
colnames(buoy)<-header
buoy = buoy %>%
  add_column(mm = NA, .after = "hh") %>%
  add_column(TIDE = NA, .after = "VIS")
#========================================================
#HANDLE YEARS 1986-2006
years <- 1986:2006
for (i in years) {
  url <- get_url(i)
  temp_data <- read.table(get_url(i), header = TRUE, sep = "",fill = TRUE)
  temp_data = temp_data %>%
    add_column(mm = NA, .after = "hh") %>%
    add_column(TIDE = NA, .after = "VIS")
  buoy <- bind_rows(buoy, temp_data)
}
buoy$YY<-na.omit(c(buoy$YY, buoy$YYYY))
buoy <- buoy %>%
  select(-YYYY, -TIDE.1, -mm.1)
colnames(buoy)[colnames(buoy) == "YY"] <- "YYYY"
#=========================================================
#HANDLE YEARS 2007-2023
years<-2007:2023
for (i in years) {
  url <- get_url(i)
  temp_data <- (read.table(get_url(i), header = FALSE, sep = "",fill = TRUE, skip=1))
  header=scan(get_url(i),what= 'character',nlines=1)
  colnames(temp_data)<-header
  buoy <- bind_rows(buoy, temp_data)
}

buoy$YYYY<-na.omit(c(buoy$YYYY, buoy$`#YY`))
buoy$BAR<-na.omit(c(buoy$BAR, buoy$PRES))
buoy <- buoy %>%
  select(-`#YY`, -PRES)

buoy$WD<-na.omit(c(buoy$WD, buoy$WDIR))
buoy <- buoy %>%
  select(-WDIR)
```


CLEAN DATA
```{r}
#Remove TIDE column because it has nothing except 99 and NA
buoy=buoy %>%
  select(-TIDE)
#set all trash data to NA
buoy$VIS<-ifelse(buoy$VIS==99, NA, buoy$VIS)
buoy$DEWP<-ifelse(buoy$DEWP==999, NA, buoy$DEWP)
buoy$MWD<-ifelse(buoy$MWD==999, NA, buoy$MWD)
buoy$APD<-ifelse(buoy$APD==99, NA, buoy$APD)
buoy$DPD<-ifelse(buoy$DPD==99, NA, buoy$DPD)
buoy$WVHT<-ifelse(buoy$WVHT==99, NA, buoy$WVHT)
buoy$BAR<-ifelse(buoy$BAR==999, NA, buoy$BAR)
buoy$ATMP<-ifelse(buoy$ATMP==999, NA, buoy$ATMP)
buoy$WTMP<-ifelse(buoy$WTMP==999, NA, buoy$WTMP)

#Add new datetime column
buoy$datetime <- ymd_h(paste(buoy$YYYY, buoy$MM, buoy$DD, buoy$hh, sep = "-"))
```

VIS NA Explanation
```{r}
#create vector over time that specifies whether the VIS index has a data reading or and NA
VIS_cat<-ifelse(is.na(buoy$VIS), "N/A", "Has Data")

#plot this vector versus time 
ggplot(buoy, aes(x = datetime, y = VIS_cat)) +
  geom_point() +
  labs(x = "Time", y = "Category", title = "ATMP vs Time")
```

ATTEMPT TO PROVE CLIMATE CHANGE (IMPOSSIBLE BECAUSE ITS A LIBERAL CONSPIRACY)
```{r}
# buoy <- buoy %>%
#   mutate(temp_moving_avg = rollmean(WTMP, k = 1000, fill = NA, align = "center"))
#   
yearly_min_temps <- buoy %>%
  group_by(year = year(datetime)) %>%
  summarise(min = min(WTMP, na.rm = TRUE))

ggplot(yearly_min_temps, aes(x = year, y = min)) +
  geom_point() +                          # Scatter plot
  geom_smooth(method = "lm", col = "red")+
  labs(title = "Minimum Yearly Temperature from 1985-2023", x = "Degrees C", y = "Year")
```


















